pipeline {
    agent any
    tools {
        go 'go-1.26'
    }

    environment {
        GO111MODULE='on'
    }
    
    stages {
        stage('Test'){
            steps{
                git 'https://github.com/thomaspalma1/jenkins-essentials.git'
                sh 'cd go-webapp-sample && go test ./...'
            }
        }
    }
}
