pipeline {
    agent any

    tools {
        go 'go1.26'
    }

    environment {
        GO111MODULE = 'on'
    }

    stages {
        stage('Test') {
            steps {
                git url: 'https://github.com/thomaspalma1/jenkins-essentials.git', branch: 'main'
                sh '''
                    cd go-webapp-sample
                    go test ./...
                '''
            }
        }
    }
}
